# Generated by Django 5.0.6 on 2024-05-15 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=True)),
                ('name', models.CharField(max_length=20)),
                ('price', models.FloatField(max_length=20)),
                ('slug', models.SlugField(max_length=30, unique=True)),
                ('image', models.ImageField(upload_to='items/')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
